services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: evapass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: evapass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=evapass"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inception-network
    extra_hosts:
    - "eprzybyl.42.fr:172.18.0.2"  # Update to MariaDB's actual container IP

  wordpress:
    image: custom-wordpress
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html
    environment:
      DB_HOST: mariadb:3306
      DB_USER: wordpress
      DB_PASSWORD: evapass
      DB_NAME: wordpress
    networks:
      - inception-network
    extra_hosts:
      - "eprzybyl.42.fr:172.18.0.4"
    

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception-network

volumes:
  mariadb-data:
    driver: local
  wordpress-data:
    driver: local

networks:
  inception-network:
    driver: bridge