version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inception-network

  wordpress:
    image: wordpress:latest
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CHARSET: ${DB_CHARSET}
      DB_COLLATE: ${DB_COLLATE}
    networks:
      - inception-network

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      inception-network:
        aliases:
          - eprzybyl.42.fr

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_DATA_PATH}
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_DATA_PATH}
      o: bind

networks:
  inception-network:
    driver: bridge
